# Generated by Django 3.2.25 on 2026-01-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjobrecord',
            name='after_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjobrecord',
            name='before_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
